version: '3'

services:
    using-docker-build:
        image: dotnet-development
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
            - DOTNET_USE_POLLING_FILE_WATCHER=1
        volumes:
            - ./:/app
            - /app/src/using-docker.web/wwwroot/lib
            - /app/src/using-docker.web/node_modules
            - /app/src/using-docker.web/bin            
            - /app/src/using-docker.web/obj
            - /app/test/using-docker.tests/bin
            - /app/test/using-docker.tests/obj
        tty: true
        working_dir: /app        
        entrypoint:
            - /bin/sh
            - -c
        command:
            - dotnet restore && cd src/using-docker.web && dotnet publish --configuration release --output /app/published