version: '2'

services:
    using-docker-test:
        image: dotnet-development
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
            - DOTNET_USE_POLLING_FILE_WATCHER=1
        volumes:
            - ./src:/app
            - ./test:/test
            - /app/using-docker.web/wwwroot/lib
            - /app/using-docker.web/bin            
            - /app/using-docker.web/obj
            - /test/using-docker.tests/bin
            - /test/using-docker.tests/obj
        tty: true
        working_dir: /test/using-docker.tests
        entrypoint:
            - /bin/sh
            - -c
        command:
            - dotnet restore && dotnet watch test