version: '2'

services:
    using-docker:
        image: dotnet-development
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
            - DOTNET_USE_POLLING_FILE_WATCHER=1
        volumes:
            - ./src:/app
            - /app/wwwroot/lib
            - /app/bin
            - /app/obj
        ports:
            - "3000:80"
        entrypoint:
            - /bin/sh
            - -c
        command:
            - dotnet restore && bower install --allow-root && dotnet watch run